### ISSUE TITLE
Mark entries as billed

### ISSUE THREAD

**Issue by dkhgh** [DefactoSoftware/Hours#205]
In the billable entries overview (#204), I want to mark one or multiple entries as __billed__, so we can keep track of which entries we have created invoices for. 
I also want to be able to un-mark an entry, for example if I accidentally marked an entry as billed.

* When selecting multiple entries, I want to see a total number of hours. 
* Entries that are marked as __billed__ cannot be changed by their owner. 
* We should record and show _who_ marked an entry as billed. I think @jurre found a nice gem for this.

**Comment by jurre** [comment]
Done
