### ISSUE TITLE
Hashtags with dashes

### ISSUE THREAD

**Issue by Marthyn** [DefactoSoftware/Hours#264]
Creating a hashtag with a dash doesn't work. So when someone tried to hashtag #E-learning it created the hashtag E. :)

![screen shot 2015-01-27 at 10 14 35](https://cloud.githubusercontent.com/assets/642544/5916095/71c1cb4e-a60d-11e4-81a1-82d1f92bd166.png)

**Comment by jurre** [comment]
![screen shot 2015-01-27 at 10 44 44](https://cloud.githubusercontent.com/assets/749864/5916437/8fd58bbc-a611-11e4-8090-3fa33064fe81.png)

The boss of hashtags behaves the same way...
