### ISSUE TITLE
Running tests clears database

### ISSUE THREAD

**Issue by Sinetheta** [DefactoSoftware/Hours#265]
Hey guys, I can appreciate that this is almost certainly something on my config, but I'm a little surprised to find things like `drop_schemas` in the spec_helper (although that is not causing the issue), so I was wondering if you have any idea what would cause a db wipe on every deploy?

It would be one thing if this were only happening locally, I mean Heroku generates it's own database.yml so I'm at a bit of a loss.

**Comment by jurre** [comment]
Hey, that is strange, and definitely not happening for me. What's in your database.yml?

The hours_test database is supposed to be cleared each time, could it be that you're pointing to the hours_development database in your test env?

**Comment by Sinetheta** [comment]
All stock. I'm trying to retrace my steps now to see where the regression comes in. Just thought you might have an idea where to check for table drops. I only noticed because the deployed version was also clearing itself periodically (haven't identified which actions trigger it).

**Comment by jurre** [comment]
Hmm no it should never do that in anything but the test environment. Are you hosting on heroku or elsewhere?

**Comment by Sinetheta** [comment]
Heroku, straight from the "deploy to heroku button". I've made very [few changes](https://github.com/Sinetheta/steam-hours/commits/master), mostly just to allow single tenant mode to work on a subdomain.

**Comment by jurre** [comment]
Yeah, I don't think your changes could cause this. Could it be that things are still written to a postgres schema matching your subdomain? You can check this by running `rails c` on heroku, then check `Account.pluck(:subdomain)` to see which accounts you have (should just be one), then you can use `Apartment::Tenant.switch "that_tenant_you_got"` to see if things are being stored in there

**Comment by Sinetheta** [comment]
I think I may have been connecting to the production DB both in dev and test. Hence test clears them both.

**Comment by jurre** [comment]
Oh! Let me know if that was the case.

**Comment by Sinetheta** [comment]
It was, but you are also right about the switch not happening. I have tests failing where `Apartment::Tenant == 'current'` but `Account.pluck(:subdomain) == 'subdomain1'`. And that's after reseting to your master branch, so it's also being affected by the environment somehow.

**Comment by jurre** [comment]
Well, the tests could create an Account which is not necessarily wrong, there is still always an account in single tenant mode, it just lives in the public schema, as do all of the other tables
