### ISSUE TITLE
Hashtags are displaced

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/Hours#285]
![screen shot 2015-02-28 at 14 20 40](https://cloud.githubusercontent.com/assets/935529/6426322/01db0cd0-bf55-11e4-9838-47acf1daf665.png)

Checked in Chrome, Safari and Firefox.

**Comment by jurre** [comment]
Yeah, I also noticed this, but I think it's new right? Not sure how this happens!

**Comment by dkhgh** [comment]
There's some pixel perfect positioning going on to display the tags. Somewhere something must have changed :p

**Comment by sn3p** [comment]
Tags get more and more displaced when the text gets longer.
