### ISSUE TITLE
Table contents of entries overflow

### ISSUE THREAD

**Issue by EwoudVeenhuizen** [DefactoSoftware/Hours#290]
![2015-03-02 14_22_49-ewoud veenhuizen _ uren](https://cloud.githubusercontent.com/assets/4919015/6441419/00125252-c0e8-11e4-81b0-10691d444ba9.png)

**Comment by Marthyn** [comment]
oh damn

**Comment by Marthyn** [comment]
It only happens with ewoud's page because he has an entry with a super long title, that <td> should be overflow: ellipsis too..
![screen shot 2015-03-02 at 15 16 41](https://cloud.githubusercontent.com/assets/642544/6442323/3c0a95e2-c0ef-11e4-957a-1982bfe31a60.png)

**Comment by sn3p** [comment]
Fixed in PR https://github.com/DefactoSoftware/Hours/pull/293

Maybe we should reconsider using icons for the actions on the right...

![screen shot 2015-03-04 at 22 17 47](https://cloud.githubusercontent.com/assets/935529/6493709/c681b7c2-c2bc-11e4-8acf-e5b9630ff14e.png)
