### ISSUE TITLE
Translation missing in signup form

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/Hours#328]
https://happyhours.io/accounts:

![screen shot 2015-06-16 at 14 18 59](https://cloud.githubusercontent.com/assets/935529/8182797/5cac4be6-1433-11e5-95e5-94122833e361.png)

but not in development.

**Comment by Marthyn** [comment]
I believe someone fixed that recently in a PR, it's just not in production yet i assume.

**Comment by Marthyn** [comment]
https://github.com/DefactoSoftware/Hours/pull/326/files

**Comment by sn3p** [comment]
Ok nice :dancer:
