### ISSUE TITLE
Changing email address

### ISSUE THREAD

**Issue by ismay** [DefactoSoftware/Hours#341]
When changing my email address (and my current password) I get the error: `translation missing: en.user_updated`, and my email address remains unchanged:

![screen shot 2015-07-20 at 16 54 30](https://cloud.githubusercontent.com/assets/7355199/8778830/5ac3e45a-2f00-11e5-9711-7f9c2206997d.png)

**Comment by jurre** [comment]
@ismay did you enter your current password? You'll receive a confirmation email that you will have to follow before your email is updated

**Comment by ismay** [comment]
> @ismay did you enter your current password?

Yeah I did. And I did receive a confirmation email (and after confirming my email was changed), so guess that it's just the flash message that wasn't working.

**Comment by jurre** [comment]
Yeah, #342 should fix that, thanks for reporting it

**Comment by ismay** [comment]
Cool, np!
