### ISSUE TITLE
rake db:migrate

### ISSUE THREAD

**Issue by devakdo** [DefactoSoftware/Hours#359]
Hi friends
           I'm getting this error while doing rake db:migrate 
 rake db:migrate

        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.

**Comment by jurre** [comment]
You can ignore this warning, it's not an error. It's because you don't have any tenants yet, so no worries :)

**Comment by ghulamjilani** [comment]
HI,
