### ISSUE TITLE
Cannot change/reset my password

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/Hours#370]
When I enter a new password (twice) I get the following message:

> Please review the problems below:

But it doesn't show what the "problems" are.

<img width="1145" alt="screen shot 2016-02-10 at 20 55 13" src="https://cloud.githubusercontent.com/assets/935529/12973717/b9926524-d0ae-11e5-9207-760e8aef1be9.png">

**Error message in the logs:**
```
Filter chain halted as :resource_from_invitation_token rendered or redirected
```

**Possible solution:**
https://github.com/scambra/devise_invitable/issues/371#issuecomment-24474473

**Comment by jurre** [comment]
In your local dev env, try adding this to the form to get it to display the errors:

```erb
  <ul>
   <% f.object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   <% end %>
 </ul>
```

**Comment by dkhgh** [comment]
```
* Slug can't be blank
* First name can't be blank
* Last name can't be blank
```

From the console: 

```ruby
#<User:0x007ff9c5c71b38
  id: 2,
  first_name: "",
  last_name: "",
  email: "hugo@learningspaces.io",
  encrypted_password: "",
  reset_password_token: nil,
  reset_password_sent_at: nil,
  remember_created_at: nil,
  sign_in_count: 0,
  current_sign_in_at: nil,
  last_sign_in_at: nil,
  current_sign_in_ip: nil,
```

**Comment by dkhgh** [comment]
So what we seem to have is: 

* A user with a confirmed account
* With no first name, last name, or password
* Who can't reset his password

**Comment by dkhgh** [comment]
In other words, it already goes wrong when confirming the account...

**Comment by dkhgh** [comment]
Updating devise invitable fixed this for me, but I'm afraid there will be some ghost users left...

**Comment by dkhgh** [comment]
@sn3p can you test this on production and let me know if it still occurs? Should be fixed.

**Comment by sn3p** [comment]
Nope :(

<img width="474" alt="screen shot 2016-04-04 at 19 19 01" src="https://cloud.githubusercontent.com/assets/935529/14256628/316bbb3a-fa9a-11e5-8208-39c51affca59.png">

**Comment by dkhgh** [comment]
Tested, fixed. @sn3p's bug is a result of a problem with confirming your account that resulted in ghost users.
