### ISSUE TITLE
Signing up 

### ISSUE THREAD

**Issue by joshbros** [DefactoSoftware/Hours#392]
I deployed the app on heroku and I just hit the following screen with no sign up option, how can I sign up?

<img width="780" alt="screen shot 2016-10-06 at 3 48 35 pm" src="https://cloud.githubusercontent.com/assets/20778665/19168065/680d6606-8bdc-11e6-87a7-5c983d20969e.png">

**Comment by dkhgh** [comment]
From the readme: 

> The first user in single tenant mode can be created by a rake task rake create_user. We'll ask you for your credentials.
