### ISSUE TITLE
5 person limit in happyhours site

### ISSUE THREAD

**Issue by nournia** [DefactoSoftware/Hours#394]
Hi,
I've create 6 accounts under my domain name in happyhours.io and I didn't receive any alert for using too many accounts. It is mentioned in your web page that only teams up to 5 persons can use this product freely. I want to know if it is a software bug, or I can use this product with how many users I want.

Also, I deployed this project using heroku button but I couldn't figure out how to signup.

Thanks.

**Comment by jurre** [comment]
It's not a hard limit, if you have 6 users that's fine, it's not a software bug :)

To set up the first user in Single Tenant mode (which the heroku button uses by default) you can use the `rake create_user` task.

**Comment by nournia** [comment]
Thanks.
