### ISSUE TITLE
Deploy master instead of development branch

### ISSUE THREAD

**Issue by jekuno** [DefactoSoftware/Hours#399]
Currently the `development` branch is set as the default branch (also see https://github.com/DefactoSoftware/Hours/branches). Therefore using https://elements.heroku.com/buttons/defactosoftware/hours (or clicking the "Deploy to Heroku" button from your main page at https://github.com/DefactoSoftware/Hours) deploys the **development branch instead of the master branch**.

**We should prevent accidental live deployments of the development system.** Therefore I would suggest to set the `master` branch as the default branch or to configure the "Deploy to Heroku" button so that it points to the `master` branch.

**Comment by fatboypunk** [comment]
I get the master branch when I click the deploy button to heroku button.
<img width="541" alt="screen shot 2017-02-20 at 18 26 20" src="https://cloud.githubusercontent.com/assets/1089927/23135728/03359cba-f79a-11e6-8bf5-d36ea2da2926.png">

But it still takes development?

> to configure the "Deploy to Heroku" button so that it points to the master branch.

I would be in favor of this one

**Comment by jekuno** [comment]
You're right, I also get the master right now - my mistake. I think we can close this issue.
