### ISSUE TITLE
While running command ./bin/setup

### ISSUE THREAD

**Issue by udkumar** [DefactoSoftware/Hours#402]
I am using Ubuntu 16.0

Bundler::GemRequireError: There was an error while trying to load the gem 'coffee-rails'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.

**Comment by udkumar** [comment]
When I add gem as below above error resolved:

gem 'execjs'
gem 'therubyracer', :platforms => :ruby

**Comment by jurre** [comment]
I think it would be solves by installing nodejs as well? I'd prefer not to add a JS runtime to the gemfile
