### ISSUE TITLE
after running "./bin/setup" getting below

### ISSUE THREAD

**Issue by udkumar** [DefactoSoftware/Hours#403]
[WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.
Pow not set up but the team uses it for this project. Setup: http://goo.gl/RaDPO
+++++++++++++++++++++++++++++++++++++++++++

# When I run migrate still getting same even with RAILS_ENV=development as well.
$ rake db:migrate
        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.

**Comment by jurre** [comment]
Do you have some more info? Like a stack trace, which env you're running on etc

**Comment by udkumar** [comment]
I have given detail above, please help me out.

**Comment by jurre** [comment]
The warning actually explains itself:

>  1. You may not have created any, in which case you can ignore this message

I'm assuming you haven't created any accounts yet, so the database is empty, so you can ignore the message :)

**Comment by udkumar** [comment]
Dear @jurre 

Where I need to create the account. Without migration how I can make any account on the local machine.

"./bin/setup" command creating the database but showing above when migration starts.

I am using ubuntu 16.0

**Comment by jurre** [comment]
Run the app and go to `/accounts/new`

**Comment by udkumar** [comment]
Hello @jurre 

When I am starting app as below, getting error:

$ foreman start
13:27:03 web.1    | started with pid 17017
13:27:03 worker.1 | started with pid 17018
13:27:03 web.1    | /home/developer/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
13:27:03 web.1    | 	from /home/developer/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
13:27:03 web.1    | 	from /usr/bin/bundle:7:in `<main>'
13:27:03 worker.1 | /home/developer/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
13:27:03 worker.1 | 	from /home/developer/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
13:27:03 worker.1 | 	from /usr/bin/bundle:7:in `<main>'
13:27:04 web.1    | exited with code 1
13:27:04 system   | sending SIGTERM to all processes
13:27:04 worker.1 | exited with code 1

Without app start how I can check /accounts/new ?

**Comment by jurre** [comment]
FYI, the migration ran just fine, it's warning, not an error. You can ignore it, like the message says.

This error seems like something related to your local setup, probably related to rvm, I'm not familiar with rvm so I can't help you with that. Try googling the error you're getting and add "rvm".
