### ISSUE TITLE
Remove Capybara-Webkit as project dependency

### ISSUE THREAD

**Issue by lym** [DefactoSoftware/Hours#488]
I suggest that we remove `capybara-webkit` as a project dependency because of the following reasons:
* The test suite as it stands can be run without this gem
* capybara-webkit depends on _qtv5.5_ which is quite problematic to install in Mac OS Mojave so this might be a potential impediment to developers who have Mojave installed

Ps: I successfully run the test suite after commenting out this gem and installing `capybara` directly. I ran the tests with the commands, `bundle exec rspec` and `bundle exec rspec spec/features`

My environment:
* Mac OS Mojave (10.14.1)

**Comment by tarzan** [comment]
I dunno, using `brew install qt@5.5` just works for me on Mojave.

**Comment by lym** [comment]
I inherited a project that used this gem some time back and I remember it was such a pain to hook up that we decided to just use Chrome headless for our headless tests. I can't find the links that I visited unfortunately.

How about the first bullet point? Do we actually use this library anywhere in the test code?

**Comment by jurre** [comment]
If it works without the gem I'm fine with removing it.
