### ISSUE TITLE
Add imagemagick as project dependency

### ISSUE THREAD

**Issue by lym** [DefactoSoftware/Hours#489]
When I ran the tests the first time, I got this error:
![image](https://user-images.githubusercontent.com/783970/55416652-e3090880-5577-11e9-8096-e4b817727bb2.png)

This was an obvious indication that I needed to install the _imagemagick_ library. I think adding this as a project dependency will be helpful for folks setting up the project for the first time.

**Comment by tarzan** [comment]
Imagemagick indeed is a an implicit dependency for converting (avatar) images. 

Feel free to add it to the Readme :)

**Comment by lym** [comment]
I will create a small PR for this.

**Comment by fatboypunk** [comment]
done in 490
