### ISSUE TITLE
How to create a user when running in single tenant node and using docker

### ISSUE THREAD

**Issue by leni1** [DefactoSoftware/Hours#507]
So I've setup Hours using the instructions in Getting Started With Docker. My problem is creating a user with `rake create_user` for the application. Is there a way to do this for those running the application with Docker?

**Comment by jurre** [comment]
The script should work, you'd just need to run it inside the docker container, have you tried that already?

**Comment by leni1** [comment]
I had tried it but against the `hours_cache_1` container :woman_facepalming: . Have run the command against the `hours_app_1` container and it worked. Thanks for the response.

P. S: For those whom Google leads here, the commands I used are in this StackOverflow answer: https://stackoverflow.com/a/31578527

**Comment by jurre** [comment]
Happy that you got it to work. Feel free to add this to the Docker section in the README.
